In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install --upgrade mxnet-cu100
!pip install autogluon

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 354.0 MB 4.8 kB/s 
  Attempting uninstall: graphviz
    Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from autogluon.vision import ImagePredictor, ImageDataset
dataset = ImageDataset.from_folder('/content/drive/MyDrive/Eye Diseases Virus Dateset Vol 1/Dataset v.2/train')

/usr/local/lib/python3.7/dist-packages/gluoncv/__init__.py:40: UserWarning: Both `mxnet==1.9.0` and `torch==1.12.1+cu113` are installed. You might encounter increased GPU memory footprint if both framework are used at the same time.
  warnings.warn(f'Both `mxnet=={mx.__version__}` and `torch=={torch.__version__}` are installed. '


In [ ]:
time_limit =  3 * 60 * 60 # 10mins
predictor = ImagePredictor()
predictor.fit(dataset, time_limit = time_limit)

INFO:autogluon.vision.predictor.predictor:Reset labels to [0, 1, 2, 3]
INFO:autogluon.vision.predictor.predictor:Randomly split train_data into train[571]/validation[64] splits.
INFO:autogluon.vision._gluoncv.image_classification:No GPU detected/allowed, using most conservative search space.
INFO:autogluon.vision._gluoncv.image_classification:Starting fit without HPO
INFO:TorchImageClassificationEstimator:modified configs(<old> != <new>): {
INFO:TorchImageClassificationEstimator:root.train.early_stop_patience -1 != 10
INFO:TorchImageClassificationEstimator:root.train.early_stop_baseline 0.0 != -inf
INFO:TorchImageClassificationEstimator:root.train.epochs    200 != 5
INFO:TorchImageClassificationEstimator:root.train.batch_size 32 != 16
INFO:TorchImageClassificationEstimator:root.train.early_stop_max_value 1.0 != inf
INFO:TorchImageClassificationEstimator:root.gpus            (0,) != ()
INFO:TorchImageClassificationEstimator:root.misc.seed       42 != 40
INFO:TorchImageClassificationEsti

In [15]:
print('Top-1 val acc: %.3f' % predictor.fit_summary()['valid_acc'])

Top-1 val acc: 0.672


In [16]:
test_dataset = ImageDataset.from_folder('/content/drive/MyDrive/Eye Diseases Virus Dateset Vol 1/Dataset v.2/test')
pred = predictor.predict(test_dataset)
print(pred)

0      2
1      2
2      0
3      0
4      0
      ..
156    3
157    3
158    3
159    3
160    3
Name: label, Length: 161, dtype: int64


In [17]:
score = predictor.evaluate(test_dataset)

INFO:TorchImageClassificationEstimator:[Epoch 1] validation: top1=0.782609 top5=1.000000


In [18]:
print(score)

{'loss': 0.5983071040292705, 'top1': 0.782608695652174, 'top5': 1.0}


In [19]:
from sklearn.metrics import confusion_matrix
ans = test_dataset.label
cm = confusion_matrix(pred,ans)
print(cm)

[[12  1  5  0]
 [ 0 24  1  2]
 [ 9 10 22  2]
 [ 0  2  3 68]]
